spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos24
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    com.pos24: DEBUG
    org.springframework.security: DEBUG 